Repository apache/flink-connector-kafka, pull requests merged in 2024-10, with the labels that each got.

#96 [FLINK-35138][Connectors/Kafka] Drop support for Flink 1.17
  .github/workflows/push_pr.yml
  .github/workflows/weekly.yml
  pom.xml
Labels: component=BuildSystem

#123 [FLINK-36422][docs] Fix PyFlink jar download link
  docs/content.zh/docs/connectors/datastream/kafka.md
  docs/content/docs/connectors/datastream/kafka.md
Labels: component=Documentation

#124 [FLINK-36422][docs] Fix PyFlink jar download link
  docs/content.zh/docs/connectors/datastream/kafka.md
  docs/content/docs/connectors/datastream/kafka.md
Labels: component=Documentation

#128 [FLINK-35109] Update version to 3.4-SNAPSHOT
  flink-connector-kafka-e2e-tests/flink-end-to-end-tests-common-kafka/pom.xml
  flink-connector-kafka-e2e-tests/flink-streaming-kafka-test-base/pom.xml
  flink-connector-kafka-e2e-tests/flink-streaming-kafka-test/pom.xml
  flink-connector-kafka-e2e-tests/pom.xml
  flink-connector-kafka/pom.xml
  flink-python/pom.xml
  flink-sql-connector-kafka/pom.xml
  pom.xml
Labels: component=Connectors/Kafka

#111 [FLINK-34467] bump flink version to 1.20.0
  .gitignore
  flink-connector-kafka/archunit-violations/86dfd459-67a9-4b26-9b5c-0b0bbf22681a
  flink-connector-kafka/archunit-violations/c0d94764-76a0-4c50-b617-70b1754c4612
  flink-connector-kafka/archunit-violations/d853eb69-8c04-4246-9a5e-4f5911286b1d
  flink-connector-kafka/archunit-violations/stored.rules
  pom.xml
Labels: component=Connectors/Kafka

#129 [FLINK-35109] Updating build configurations for v3.3
  .github/workflows/push_pr.yml
  .github/workflows/weekly.yml
Labels: component=BuildSystem

#131 [FLINK-35109] Update website data for 3.3.0
  docs/data/kafka.yml
Labels: component=Documentation

#132 [FLINK-36595][docs] Explicitly set connector compatibility as string to prevent version comparison mismatch
  docs/data/kafka.yml
Labels: component=Documentation
